# Generated by Django 6.0.5 on 2026-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='copyright_year',
            field=models.CharField(default='2026', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='footer_text',
            field=models.CharField(default='Built with Django', max_length=200),
        ),
    ]
