# Generated by Django 6.0.5 on 2026-05-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_profile_copyright_year_profile_footer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='copyright_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='footer_text',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
