# Generated by Django 6.0.5 on 2026-05-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_profile_copyright_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, help_text='உங்களைப் பற்றி இங்கே எழுதவும்'),
        ),
    ]
