# Generated by Django 6.0.5 on 2026-05-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_title',
            field=models.CharField(default='My Project Portfolio', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_title',
            field=models.CharField(default='Java Developer | Django Enthusiast', max_length=200),
        ),
    ]
