# Generated by Django 6.0.5 on 2026-05-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_contact_subject_profile_about_me_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cropping',
        ),
    ]
